language: en
pipeline:
- name: "SpacyNLP"
  model: "en_trf_distilbertbaseuncased_lg"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"

policies:
- epochs: 300
  max_history: 5
  name: KerasPolicy
- name: TwoStageFallbackPolicy
  nlu_threshold: 0.6
  core_threshold: 0.3
- max_history: 5
  name: MemoizationPolicy
- name: MappingPolicy
