language: en
pipeline: pretrained_embeddings_spacy
policies:
- epochs: 300
  max_history: 5
  name: KerasPolicy
- name: TwoStageFallbackPolicy
  nlu_threshold: 0.6
  core_threshold: 0.3
- max_history: 5
  name: MemoizationPolicy
- name: MappingPolicy
