version: '3'
services:
  rasa:
    image: aj-estonia
    container_name: rasa-server
    networks: ["rasa-network"]
    restart: always
    ports:
      - "5005:5005"
    volumes:
      - ./models/:/app/models
  actions:
    image: aj-lithuania
    container_name: rasa-actions-server
    networks: ["rasa-network"]
    restart: always
    ports:
      - "5055:5055"

networks:
  rasa-network: {}
