version: '3'
services:
  rasa:
    image: aj-estonia
    container_name: rasa-server
    depends_on:
      - rasa-actions
    ports:
      - "5005:5005"
    networks:
      - "net1"
    links:
      - rasa-actions:rasa-actions
  rasa-actions:
    image: aj-lithuania
    container_name: rasa-actions-server
    ports:
      - "5055:5055"
    networks:
      - "net1"

networks:
  net1:
    driver: bridge
